#! /bin/sh

if [ ! -d ~/packages ]
then
	mkdir -p ~/packages
fi

pushd ~/packages

if [ -f .git ]
then
	git init		
fi

echo $1 >> packages.python
sudo apt-get install -y $1 

git add packages.python
git commit -m "Adding python package: $1"

popd
