#! /bin/bash

if [ ! -d ~/packages ]
then
	mkdir -p ~/packages
fi

pushd ~/packages

if [ ! -d .git ]
then
	git init		
fi

`which yum`
yum=$?

if [ $yum ]
then
	sudo yum -y install $1
else
	sudo apt-get install -y $1
fi

echo $1 >> packages.system
git add packages.system
git commit -m "Adding system package: $1"

popd
