#! /bin/bash

if [ ! -d ~/packages ]
then
	mkdir -p ~/packages
fi

pushd ~/packages

if [ ! -d .git ]
then
	git init		
fi

echo $1 >> packages.system
sudo apt-get install -y $1 

git add packages.system
git commit -m "Adding system package: $1"

popd
